# Generated by Django 4.2.23 on 2025-08-14 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('grade', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('is_active', models.BooleanField(default=True)),
                ('midterm_score', models.IntegerField()),
                ('final_exam_score', models.IntegerField()),
            ],
        ),
    ]
