# Generated by Django 4.2.23 on 2025-08-15 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_created_at_student_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.CharField(choices=[('AA', 'AA'), ('BB', 'BB'), ('CC', 'CC'), ('DD', 'DD'), ('FF', 'FF')], max_length=2),
        ),
    ]
